### ISSUE TITLE
[ED - Biz Case] References - show, hide & size & format

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#30] opened 2018-08-02 18:21 UTC
I agree that the references are important. (and recognize all the work that went into the research!)

To make them available for those who need proof or want more info *and* decrease clutter for others, ideas:
* Reference section collapsed by default
* References section uses smaller font
* Overall option to show or hide references. This would hide the little numbers throughout the text. Of course, adding that button would add some complexity, too, so not sure if worth it?

I don't feel strongly about any of it.

**Comment by yatil** [comment] 2018-08-03 07:07
I don’t like cluttering the interface with options. I think when the references are at the end, people who are not interested in seeing them can just skip over, and the same goes for the “little numbers”. I think it is a learned convention.

For the reference section: This is yet unstyled, as it is shaping form I create an issue and will work on it. Due to the references being in the Markdown text themselves, we’re a bit limited on what we can do easily as we have to add necessary elements using JavaScript (for example an expand/collapse section would probably need a re-write or at least serious look at of that complete logic).

**Comment by yatil** [comment] 2018-08-03 07:31
On the actual text formatting: Do we need to have the URLs written out like that in the references section or could we just link the actual title of the work? I think that would make the list easier to scan, especially for screen reader users. I don't have a strong idea of how references like that should work, and I know there are certain standards but do we need to follow them to the letter or can we make adjustments for accessibility?

I would make sure that a print stylesheet would show the URLs. (_Note to self: you forgot to do a print stylesheet._)

Would be interested in your thoughts, @slhenry and @sharronrush.

**Comment by sharronrush** [comment] 2018-08-26 03:58
@slhenry  My position is to leave to the discretion of the implementer   -  @yatil 
may we close the issue and leave this to Eric?

**Comment by yatil** [comment] 2018-08-26 10:36
@sharronrush The remainder of the issue is the formatting of the text of the actual footnotes, to make it less formal. If you want I’m happy to re-format it.

**Comment by sharronrush** [comment] 2018-08-26 12:34
Thank you @yatil I would appreciate that!

**Comment by yatil** [comment] 2018-08-27 10:56
Done! 6b2f93b82e2f0adacb2b80b70e3d150c59e73b7c

**Closed by yatil** 2018-08-27 10:57 UTC
